admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    path:     /
    defaults:  { _controller: AdminBundle:EmployeeInformation:renderData }